/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;


@javax.ws.rs.ApplicationPath("BusServer")
public class ApplicationConfig extends Application {

    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(org.feup.cmov.bus.AvailableTicketsResource.class);
        resources.add(org.feup.cmov.bus.BuyTicketsResource.class);
        resources.add(org.feup.cmov.bus.PurchaseHistoryResource.class);
        resources.add(org.feup.cmov.bus.TicketHistoryResource.class);
        resources.add(org.feup.cmov.bus.TicketResource.class);
        resources.add(org.feup.cmov.bus.UserResource.class);
        return resources;
    }
    
}
